version: "3"
services:
  jupyter:  # 立ち上げるサービスの名称(コンテナ名を指定しない場合，これが利用される)
    image: kaggle_base:latest  # imageの指定
    container_name: soccer_jupyter  # コンテナ名
    volumes:
      - $PWD:/project
    working_dir: /project/
    ports:
      - 7777:8888
    command: jupyter notebook --port 8888
  
  mlflow:  # 立ち上げるサービスの名称(コンテナ名を指定しない場合，これが利用される)
    image: kaggle_base:latest  # imageの指定
    container_name: soccer_mlflow  # コンテナ名
    volumes:
      - $PWD:/project
    working_dir: /project/
    ports:
      - 5000:5000
    command: mlflow ui --backend-store-uri /project/src/mlruns --host 0.0.0.0 --port 5000
